# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhiyuan Yang
description: >- # this means to ignore newlines until "baseurl:"
  Zhiyuan's personal website.
url: "https://ziyuen.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Work
    - name: Blog

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: zhiyuan.yang.cs@outlook.com
      link: zhiyuan.yang.cs@outlook.com
  follow:
    - name: LinkedIn
      link: https://www.linkedin.com/in/zhiyuan-yang-52151b10b
    - name: GitHub
      link: https://github.com/ziyuen

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
